use lumine;

DROP VIEW IF EXISTS VISTA_ARCHIVO;
CREATE VIEW VISTA_ARCHIVO AS
SELECT * FROM archivo;

DROP VIEW IF EXISTS VISTA_CATEGORIA;
CREATE VIEW VISTA_CATEGORIA AS
SELECT * FROM categoria;

DROP VIEW IF EXISTS VISTA_COMENTARIOS;
CREATE VIEW VISTA_COMENTARIOS AS
SELECT * FROM comentarios;

DROP VIEW IF EXISTS VISTA_CONTRASEÑA;
CREATE VIEW VISTA_CONTRASEÑA AS
SELECT * FROM contraseña;

DROP VIEW IF EXISTS VISTA_ESTADO_OVA;
CREATE VIEW VISTA_ESTADO_OVA AS
SELECT estado FROM estado_ova;

DROP VIEW IF EXISTS VISTA_GRUPO;
CREATE VIEW VISTA_GRUPO AS
SELECT * FROM grupo;

DROP VIEW IF EXISTS VISTA_METADATOS;
CREATE VIEW VISTA_METADATOS AS
SELECT * FROM metadatos;

DROP VIEW IF EXISTS VISTA_OVA;
CREATE VIEW VISTA_OVA AS
SELECT * FROM ova;

DROP VIEW IF EXISTS VISTA_PARAMETROS;
CREATE VIEW VISTA_PARAMETROS AS
SELECT * FROM parametros;

DROP VIEW IF EXISTS VISTA_PERMISOS;
CREATE VIEW VISTA_PERMISOS AS
SELECT * FROM permisos;

DROP VIEW IF EXISTS VISTA_PREGUNTAS;
CREATE VIEW VISTA_PREGUNTAS AS
SELECT * FROM preguntas;

DROP VIEW IF EXISTS VISTA_PREGUNTAS_USUARIOS;
CREATE VIEW VISTA_PREGUNTAS_USUARIOS AS
SELECT * FROM preguntas_usuarios;

DROP VIEW IF EXISTS VISTA_PUNTUACION;
CREATE VIEW VISTA_PUNTUACION AS
SELECT valor, idOva, idUsuario FROM puntuacion;

DROP VIEW IF EXISTS VISTA_ROLES;
CREATE VIEW VISTA_ROLES AS
SELECT * FROM roles;

DROP VIEW IF EXISTS VISTA_TIPO_OVA;
CREATE VIEW VISTA_TIPO_OVA AS
SELECT * FROM tipo_ova;

DROP VIEW IF EXISTS VISTA_USUARIO;
CREATE VIEW VISTA_USUARIO AS
SELECT * FROM usuario;

